config/routes.rb
Rails.application.routes.draw do
  root "followers#index"

  resources :followers do
    resources :posts
  end

  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commet.rb
class Commet < ApplicationRecord
  before_save :check_author
  belongs_to :post

  def check_author
    if self.author.blank?
      self.author = 'anon'
    end
  end
end

app/models/follower.rb
class Follower < ApplicationRecord
  has_many :posts

  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :follower
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def new
    @comment = Comment.new
  end

  def create
    @comment = post.comments.new(comment_params)
    if @comment.save
      redirect_to follower_post_path(@post.follower_id, @post)
    else
      render :new
  end

  private
    def set_post
      @post = Post.find(params[:post_id])
    end

    def comment_params
      params.require(:comment).permit(:body, :author)
    end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  def index
    @followers = Follower.all
  end

  def show
  end

  def new
    @follower = Follower.new
    render partial: "form"
  end

  def create
    @follower = Follower.new(follower_params)

    if @follower.save
      redirect_to followers_path
    else
      render :new
    end
  end

  def update
    if @follower.update(follower_params)
      redirect_to @follower
    else
      render :edit
    end
  end

  def destroy
    @follower.destroy
    redirect_to folllowers_path
  end

  def edit
    render partial: "form"
  end

  private

    def set_follower
      @follower = Follower.find(params[:id])
    end

    def follower_params
      params.require(:follower).permit(:name)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_follower
  before_action :set_follower, only: [:show, :edit, :update, :destroy]

  def index
    @posts = @follower.posts
  end

  def show
  end

  def new
    @post = @follower.posts.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @post = @follower.posts.new(post_params)

    if @post.save
      redirect_to [@follower, @post]
    else
      render :new
    end
  end

  def update
    if @post.update(topic_params)
      redirect_to [@follower, @post]
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to follower_posts_path(@follower)
  end

  private

    def set_follower
      @follower = Follower.find(params[:follower_id])
    end

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:name, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<hr />
<p>Author: <%= comment.author %></p>
<p><strong><%= comment.body %><strong></p>
</hr> 

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Add a comment</h1>
<%= form_for [@post, @comment] do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <br />
  <%= f.label :author%>
  <%= f.text_area :author, placeholder: 'leave blank to anonymous' %>
  <br />
  <%= f.submit %>
<% end %>

app/views/followers/_form.html.erb
<h1><%= @follower.id ? 'Edit Follower' : 'Create Follower' %></h1>
<hr />
<%= form_for @follower do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %> 

app/views/followers/edit.html.erb
<h1>Followers#edit</h1>
<p>Find me in app/views/followers/edit.html.erb</p>

app/views/followers/index.html.erb
<h1>Click a follower to view</h1>
<%= link_to 'Create a new follower', new_follower_path %>
<ul>
  <% @followers.each do |follower| %>
    <li><%= link_to follower.name, follower %></li>
    <% end %>
</ul>

app/views/followers/new.html.erb
<h1>Followers#new</h1>
<p>Find me in app/views/followers/new.html.erb</p>

app/views/followers/show.html.erb
<h1> <%= @follower.name %> </h1>
<hr />
<p> What would you like to do? </p>
<%= link_to "View post", follower_post_path(@follower) %>
<br />
<%= link_to 'Edit follower', edit_follower_path(@follower) %>
<br />
<%= link_to 'Delete follower', @follower, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fourchan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<h1><%= @post.id ? 'edit post' : "Create post" %></h1>
<hr />
<%= form_for [@follower, @post] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :body %>
  <%= f.text_area :name, required: true %>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<h1>Click a post to view content</h1>
<%= link_to 'Create a new post', new_sub_post_path(@follower) %>
<ul>
  <% @posts.each do |post| %>
    <li><%= link_to post.name, [@follower, post] %></li>
    <% end %>
</ul>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/show.html.erb
<h1><%= @follower.name %> - <%= @post.name %> </h1>
<p> <%= @post.body %></p>
<hr>Comments</h2>

<% @post.comments.each do |comment| %>
  <%= render 'comment/comment', {comment: comment } %>
<% end %>

<hr />
<%= link_to 'add comment', new_post_comment_path(@post) %>
<%= link_to 'edit post', edit_follower_post_path([@follower, @post]) %>
<%= link_to 'delete post', [@follower, @post], method: :delete %>
<%= link_to 'back to posts', follower_posts_path(@follower)